# Generated by Django 5.1 on 2024-10-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_urlvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
